default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: user
  password: password
  host: localhost

development:
  <<: *default
  database: studytimer_back_development

test:
  <<: *default
  database: studytimer_back_test

production:
  <<: *default
  database: studytimer_back_production
  username: studytimer_back
  password: <%= ENV["STUDYTIMER_BACK_DATABASE_PASSWORD"] %>
